// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectOBS() {
  return window['go']['main']['App']['ConnectOBS']();
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DisconnectOBS() {
  return window['go']['main']['App']['DisconnectOBS']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetScenes() {
  return window['go']['main']['App']['GetScenes']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function GetSources(arg1) {
  return window['go']['main']['App']['GetSources'](arg1);
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function RestartServer() {
  return window['go']['main']['App']['RestartServer']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SetRecording(arg1) {
  return window['go']['main']['App']['SetRecording'](arg1);
}

export function SetScene(arg1) {
  return window['go']['main']['App']['SetScene'](arg1);
}

export function SetSourceVisible(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSourceVisible'](arg1, arg2, arg3);
}

export function SetStreaming(arg1) {
  return window['go']['main']['App']['SetStreaming'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function SwitchProfile(arg1) {
  return window['go']['main']['App']['SwitchProfile'](arg1);
}

export function TestOBS() {
  return window['go']['main']['App']['TestOBS']();
}
