// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {logs} from '../models';
import {obs} from '../models';

export function ConnectOBS():Promise<void>;

export function DisconnectOBS():Promise<void>;

export function GetConfig():Promise<main.ConfigView>;

export function GetLogs(arg1:string):Promise<Array<logs.Entry>>;

export function GetScenes():Promise<Array<obs.Scene>>;

export function GetSnapshot():Promise<main.Snapshot>;

export function RestartServer():Promise<void>;

export function SaveConfig(arg1:main.ConfigView,arg2:string):Promise<void>;

export function SetScene(arg1:string):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function TestOBS():Promise<void>;
