// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectOBS() {
  return window['go']['main']['App']['ConnectOBS']();
}

export function DisconnectOBS() {
  return window['go']['main']['App']['DisconnectOBS']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetScenes() {
  return window['go']['main']['App']['GetScenes']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function RestartServer() {
  return window['go']['main']['App']['RestartServer']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SetScene(arg1) {
  return window['go']['main']['App']['SetScene'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function TestOBS() {
  return window['go']['main']['App']['TestOBS']();
}
